# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create ATRIA searcher (ball-tree).
#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param x PARAM_DESCRIPTION
#' @param metric PARAM_DESCRIPTION, Default: 'euclidian'
#' @param exclude_samples PARAM_DESCRIPTION, Default: 0
#' @param cluster_max_points PARAM_DESCRIPTION, Default: 64
#' @param seed PARAM_DESCRIPTION, Default: 93453562
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname create_searcher
#' @export
create_searcher <- function(x, metric = "euclidian", exclude_samples = 0L, cluster_max_points = 64L, seed = 93453562L) {
    .Call(`_atriar_create_searcher`, x, metric, exclude_samples, cluster_max_points, seed)
}

#' Release searcher
#'
#' Destroy ATRIA searcher object and free all allocated memory.
#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param searcher PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname release_searcher
#' @export
release_searcher <- function(searcher) {
    .Call(`_atriar_release_searcher`, searcher)
}

#' Number of points,
#'
#' Return number of points used to create the searcher.
#'
#' @param searcher An exernal pointer to an ATRIA searcher.
#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param searcher PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname number_of_points
#' @export
number_of_points <- function(searcher) {
    .Call(`_atriar_number_of_points`, searcher)
}

#' Data set radius
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param searcher PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname data_set_radius
#' @export
data_set_radius <- function(searcher) {
    .Call(`_atriar_data_set_radius`, searcher)
}

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param searcher PARAM_DESCRIPTION
#' @param k PARAM_DESCRIPTION
#' @param query_points PARAM_DESCRIPTION
#' @param exclude PARAM_DESCRIPTION, Default: matrix()
#' @param epsilon PARAM_DESCRIPTION, Default: 0
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname search_k_neighbors
#' @export
search_k_neighbors <- function(searcher, k, query_points, exclude = matrix(), epsilon = 0) {
    .Call(`_atriar_search_k_neighbors`, searcher, k, query_points, exclude, epsilon)
}

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param searcher PARAM_DESCRIPTION
#' @param radius PARAM_DESCRIPTION
#' @param query_points PARAM_DESCRIPTION
#' @param exclude PARAM_DESCRIPTION, Default: matrix()
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname search_range
#' @export
search_range <- function(searcher, radius, query_points, exclude = matrix()) {
    .Call(`_atriar_search_range`, searcher, radius, query_points, exclude)
}

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param x PARAM_DESCRIPTION
#' @param verbose PARAM_DESCRIPTION, Default: FALSE
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname boxcount
#' @export
boxcount <- function(x, verbose = FALSE) {
    .Call(`_atriar_boxcount`, x, verbose)
}

#' Compute a histogram of positive integers.
#'
#' Fast counting of positve integers in input vector bins.
#'
#' @param bins An integer vector with positive entries only.
#' @param max_bin An integer with the maximum expected bin in bins.
#' @export
count_integers <- function(bins, max_bin = -1L) {
    .Call(`_atriar_count_integers`, bins, max_bin)
}

#' Leading NA
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
henon <- function(length = 2000L, params = as.numeric( c()), transient = 5000L) {
    .Call(`_atriar_henon`, length, params, transient)
}

